**Multiple linear regression**


1. Create a regression model using Multiple linear regression for the given dataset.
Tips: Follow the same procedure as in simple linear but change the independent variable range and plot the model
Use feature scaling or standardisation procedure.
You can refer videos in YouTube for the same.


Dataset: https://drive.google.com/file/d/1-mRFkOXOgk0w7ZUweWJ_9TyqJmGFDbG2/view?usp=sharing

In [117]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [118]:
df = pd.read_csv('50_Startups.csv')
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [119]:
df.drop('State', inplace=True, axis=1)
df

R&D Spend  Administration  Marketing Spend     Profit
0   165349.20       136897.80        471784.10  192261.83
1   162597.70       151377.59        443898.53  191792.06
2   153441.51       101145.55        407934.54  191050.39
3   144372.41       118671.85        383199.62  182901.99
4   142107.34        91391.77        366168.42  166187.94
5   131876.90        99814.71        362861.36  156991.12
6   134615.46       147198.87        127716.82  156122.51
7   130298.13       145530.06        323876.68  155752.60
8   120542.52       148718.95        311613.29  152211.77
9   123334.88       108679.17        304981.62  149759.96
10  101913.08       110594.11        229160.95  146121.95
11  100671.96        91790.61        249744.55  144259.40
12   93863.75       127320.38        249839.44  141585.52
13   91992.39       135495.07        252664.93  134307.35
14  119943.24       156547.42        256512.92  132602.65
15  114523.61       122616.84        261776.23  129917.04
16   78013.11       121597.55        264346.06  126992.93
17   94657.16       145077.58        282574.31  125370.37
18   91749.16       114175.79        294919.57  124266.90
19   86419.70       153514.11             0.00  122776.86
20   76253.86       113867.30        298664.47  118474.03
21   78389.47       153773.43        299737.29  111313.02
22   73994.56       122782.75        303319.26  110352.25
23   67532.53       105751.03        304768.73  108733.99
24   77044.01        99281.34        140574.81  108552.04
25   64664.71       139553.16        137962.62  107404.34
26   75328.87       144135.98        134050.07  105733.54
27   72107.60       127864.55        353183.81  105008.31
28   66051.52       182645.56        118148.20  103282.38
29   65605.48       153032.06        107138.38  101004.64
30   61994.48       115641.28         91131.24   99937.59
31   61136.38       152701.92         88218.23   97483.56
32   63408.86       129219.61         46085.25   97427.84
33   55493.95       103057.49        214634.81   96778.92
34   46426.07       157693.92        210797.67   96712.80
35   46014.02        85047.44        205517.64   96479.51
36   28663.76       127056.21        201126.82   90708.19
37   44069.95        51283.14        197029.42   89949.14
38   20229.59        65947.93        185265.10   81229.06
39   38558.51        82982.09        174999.30   81005.76
40   28754.33       118546.05        172795.67   78239.91
41   27892.92        84710.77        164470.71   77798.83
42   23640.93        96189.63        148001.11   71498.49
43   15505.73       127382.30         35534.17   69758.98
44   22177.74       154806.14         28334.72   65200.33
45    1000.23       124153.04          1903.93   64926.08
46    1315.46       115816.21        297114.46   49490.75
47       0.00       135426.92             0.00   42559.73
48     542.05        51743.15             0.00   35673.41
49       0.00       116983.80         45173.06   14681.40

In [120]:
reg = linear_model.LinearRegression()
reg.fit(df[['R&D Spend',	'Administration',	'Marketing Spend']], df.Profit)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [121]:
reg.coef_

array([ 0.80571505, -0.02681597,  0.02722806])

In [122]:
reg.intercept_

50122.19298986523

In [123]:
reg.predict([[72107.60,127864.55,353183.81]])

array([114408.07145684])

In [124]:
from sklearn.preprocessing import StandardScaler

In [125]:
scaling = StandardScaler()

In [126]:
scaling.fit_transform(df[['R&D Spend',	'Administration',	'Marketing Spend']])

array([[ 2.01641149e+00,  5.60752915e-01,  2.15394309e+00],
       [ 1.95586034e+00,  1.08280658e+00,  1.92360040e+00],
       [ 1.75436374e+00, -7.28257028e-01,  1.62652767e+00],
       [ 1.55478369e+00, -9.63646307e-02,  1.42221024e+00],
       [ 1.50493720e+00, -1.07991935e+00,  1.28152771e+00],
       [ 1.27980001e+00, -7.76239071e-01,  1.25421046e+00],
       [ 1.34006641e+00,  9.32147208e-01, -6.88149930e-01],
       [ 1.24505666e+00,  8.71980011e-01,  9.32185978e-01],
       [ 1.03036886e+00,  9.86952101e-01,  8.30886909e-01],
       [ 1.09181921e+00, -4.56640246e-01,  7.76107440e-01],
       [ 6.20398248e-01, -3.87599089e-01,  1.49807267e-01],
       [ 5.93085418e-01, -1.06553960e+00,  3.19833623e-01],
       [ 4.43259872e-01,  2.15449064e-01,  3.20617441e-01],
       [ 4.02077603e-01,  5.10178953e-01,  3.43956788e-01],
       [ 1.01718075e+00,  1.26919939e+00,  3.75742273e-01],
       [ 8.97913123e-01,  4.58678535e-02,  4.19218702e-01],
       [ 9.44411957e-02,  9.11841968e-03

In [127]:
df.head

<bound method NDFrame.head of     R&D Spend  Administration  Marketing Spend     Profit
0   165349.20       136897.80        471784.10  192261.83
1   162597.70       151377.59        443898.53  191792.06
2   153441.51       101145.55        407934.54  191050.39
3   144372.41       118671.85        383199.62  182901.99
4   142107.34        91391.77        366168.42  166187.94
5   131876.90        99814.71        362861.36  156991.12
6   134615.46       147198.87        127716.82  156122.51
7   130298.13       145530.06        323876.68  155752.60
8   120542.52       148718.95        311613.29  152211.77
9   123334.88       108679.17        304981.62  149759.96
10  101913.08       110594.11        229160.95  146121.95
11  100671.96        91790.61        249744.55  144259.40
12   93863.75       127320.38        249839.44  141585.52
13   91992.39       135495.07        252664.93  134307.35
14  119943.24       156547.42        256512.92  132602.65
15  114523.61       122616.84        26177

In [128]:
y = df.iloc[:,:1].values
y

array([[165349.2 ],
       [162597.7 ],
       [153441.51],
       [144372.41],
       [142107.34],
       [131876.9 ],
       [134615.46],
       [130298.13],
       [120542.52],
       [123334.88],
       [101913.08],
       [100671.96],
       [ 93863.75],
       [ 91992.39],
       [119943.24],
       [114523.61],
       [ 78013.11],
       [ 94657.16],
       [ 91749.16],
       [ 86419.7 ],
       [ 76253.86],
       [ 78389.47],
       [ 73994.56],
       [ 67532.53],
       [ 77044.01],
       [ 64664.71],
       [ 75328.87],
       [ 72107.6 ],
       [ 66051.52],
       [ 65605.48],
       [ 61994.48],
       [ 61136.38],
       [ 63408.86],
       [ 55493.95],
       [ 46426.07],
       [ 46014.02],
       [ 28663.76],
       [ 44069.95],
       [ 20229.59],
       [ 38558.51],
       [ 28754.33],
       [ 27892.92],
       [ 23640.93],
       [ 15505.73],
       [ 22177.74],
       [  1000.23],
       [  1315.46],
       [     0.  ],
       [   542.05],
       [     0.  ]])

In [129]:
x = df.iloc[:,1:].values
x

array([[136897.8 , 471784.1 , 192261.83],
       [151377.59, 443898.53, 191792.06],
       [101145.55, 407934.54, 191050.39],
       [118671.85, 383199.62, 182901.99],
       [ 91391.77, 366168.42, 166187.94],
       [ 99814.71, 362861.36, 156991.12],
       [147198.87, 127716.82, 156122.51],
       [145530.06, 323876.68, 155752.6 ],
       [148718.95, 311613.29, 152211.77],
       [108679.17, 304981.62, 149759.96],
       [110594.11, 229160.95, 146121.95],
       [ 91790.61, 249744.55, 144259.4 ],
       [127320.38, 249839.44, 141585.52],
       [135495.07, 252664.93, 134307.35],
       [156547.42, 256512.92, 132602.65],
       [122616.84, 261776.23, 129917.04],
       [121597.55, 264346.06, 126992.93],
       [145077.58, 282574.31, 125370.37],
       [114175.79, 294919.57, 124266.9 ],
       [153514.11,      0.  , 122776.86],
       [113867.3 , 298664.47, 118474.03],
       [153773.43, 299737.29, 111313.02],
       [122782.75, 303319.26, 110352.25],
       [105751.03, 304768.73, 1087

In [130]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [131]:
x_test.shape

(10, 3)

In [132]:
from sklearn.linear_model import LinearRegression

In [133]:
regressor = LinearRegression()

In [134]:
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [135]:
pred = regressor.predict(x_test)

In [136]:
pred

array([[ 67258.09226298],
       [108902.84071903],
       [111717.7647248 ],
       [ 35267.87434892],
       [160681.13395262],
       [ 66568.02228168],
       [ 38312.72396617],
       [ 59785.24741845],
       [ 72408.43056122],
       [132891.11211054]])

In [137]:
y_test

array([[ 66051.52],
       [100671.96],
       [101913.08],
       [ 27892.92],
       [153441.51],
       [ 72107.6 ],
       [ 20229.59],
       [ 61136.38],
       [ 73994.56],
       [142107.34]])

Q2) 
Create a DataFrame in python and make Date column as index:
Date Temperature Rainfall Mosquitos

01/01/2020 20 1.1 150

02/01/2020 18 0.6 217

03/01/2020 19 0.9 153

04/01/2020 20 1.0 158

Give codes and outputs for following statements:
1. Code to return the Temperature and Rainfall of rows 2 and 3.
2. Code to return max temperature from Temperature column.
3. Code to return min rainfall from Rainfall column.
4. Average from Mosquitos column.

In [138]:
l1 = [('01/01/2020', 20, 1.1, 150), ('02/01/2020', 18, 0.6, 217),('03/01/2020', 19, 0.9, 153),('04/01/2020', 20, 1.0, 158)]
data = pd.DataFrame(l1, columns=['Date','Temperature','Rainfall','Mosquitos'])
data

Date  Temperature  Rainfall  Mosquitos
0  01/01/2020           20       1.1        150
1  02/01/2020           18       0.6        217
2  03/01/2020           19       0.9        153
3  04/01/2020           20       1.0        158

In [139]:
data.loc[1:2, ['Temperature','Rainfall'] ]

Temperature  Rainfall
1           18       0.6
2           19       0.9

In [140]:
data.iloc[1:3, 1:3 ]

Temperature  Rainfall
1           18       0.6
2           19       0.9

In [141]:
data.dtypes

Date            object
Temperature      int64
Rainfall       float64
Mosquitos        int64
dtype: object

In [142]:
# Highest temperature
data.Temperature.max()

20

In [143]:
# Lowest Rainfall
data.Rainfall.min()

0.6

In [144]:
data.Mosquitos.mean()

169.5